[project]
name = "ai-vs-human-detector"
version = "0.1.0"
description = "AI vs Human text detector"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "fastapi",
    "uvicorn",
    "scikit-learn",
    "pandas",
    "numpy",
    "pickle-mixin",
    "requests",
    "jinja2",
    "pytest>=9.0.2",
    "httpx>=0.27.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "httpx>=0.27.0",
]
