name: CI/CD Pipeline IA

# Aquí decidimos cuándo se activa el "BOOM".
# Cada vez que se haga push o se haga un pull request.
# en las ramas 'main' o 'dev', esta maquina se pondrá a trabajar sola.
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test-and-build:
    # Le pedimos a GitHub una máquina virtual con Linux (Ubuntu) para que haga automatice el proceso!
    runs-on: ubuntu-latest

    steps:
      # La maquina se descarga una copia de nuestro código.
      - name: Checkout code
        uses: actions/checkout@v4

      # Instala 'uv', que es nuestro gestor de paquetes ultra rápido.
      # Usa caché para que no tenga que descargar todo desde cero cada vez.
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      # Instala las librerías del proyecto y lanza los tests.
      # Si un test falla, el proceso se detiene aquí y nos avisa.
      - name: Install dependencies and run tests
        run: |
          cd ai-vs-human-detector
          uv sync
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          uv run pytest test/

      # Prepara las herramientas para construir imágenes de Docker/
      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Intenta construir la imagen de Docker con nuestro Pipeline
      # De momento no la subimos a ningún sitio (push: false), solo comprobamos 
      # que el Dockerfile funciona y que la imagen es estable.
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ai-vs-human-detector
          push: false
          tags: ai-human-classifier:latest
